#!/usr/bin/env python3
"""block-generated: PreToolUse hook that blocks edits to generated files.

Reads the tool-input JSON payload from stdin. For Edit/Write/MultiEdit/NotebookEdit
tools, checks whether the target file lives in a generated directory or has a
well-known generated marker in its first few lines. Exits 2 with a message on
stderr if so - Claude sees the block and must choose a different target.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BLOCKED_SEGMENTS = {
    "generated",
    "__generated__",
    "dist",
    "build",
    ".next",
    "node_modules",
    "__pycache__",
    "target",
    "out",
    ".gradle",
}

GENERATED_MARKERS = ("@generated", "DO NOT EDIT", "AUTO-GENERATED", "autogenerated")
MARKER_SCAN_LINES = 5


def _extract_path(payload: dict) -> str | None:
    tool_input = payload.get("tool_input") or {}
    return (
        tool_input.get("file_path")
        or tool_input.get("notebook_path")
        or tool_input.get("path")
    )


def _segment_hit(path: Path) -> str | None:
    for part in path.parts:
        if part in BLOCKED_SEGMENTS:
            return part
    return None


def _marker_hit(path: Path) -> str | None:
    if not path.exists() or not path.is_file():
        return None
    try:
        with path.open("r", encoding="utf-8", errors="ignore") as fh:
            for i, line in enumerate(fh):
                if i >= MARKER_SCAN_LINES:
                    break
                for marker in GENERATED_MARKERS:
                    if marker in line:
                        return marker
    except OSError:
        return None
    return None


def main() -> int:
    try:
        payload = json.loads(sys.stdin.read() or "{}")
    except json.JSONDecodeError:
        return 0

    if payload.get("tool_name") not in {"Edit", "Write", "MultiEdit", "NotebookEdit"}:
        return 0

    raw = _extract_path(payload)
    if not raw:
        return 0

    target = Path(raw)
    cwd = Path(payload.get("cwd") or ".")
    try:
        rel = target.resolve().relative_to(cwd.resolve()).as_posix()
    except (ValueError, OSError):
        rel = target.as_posix()

    segment = _segment_hit(Path(rel))
    if segment:
        print(
            f"BLOCKED: {rel} lives under a generated directory ('{segment}'). "
            "Edit the source or regenerate via the project's codegen command.",
            file=sys.stderr,
        )
        return 2

    if ".generated." in target.name or ".gen." in target.name:
        marker_name = ".generated." if ".generated." in target.name else ".gen."
        print(
            f"BLOCKED: {rel} has a '{marker_name}' filename marker. "
            "Edit the source template instead.",
            file=sys.stderr,
        )
        return 2

    marker = _marker_hit(target)
    if marker:
        print(
            f"BLOCKED: {rel} header contains '{marker}'. "
            "This file is machine-generated - edit its source.",
            file=sys.stderr,
        )
        return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
